### ISSUE TITLE
Keyboard not working with RDP windows host using iOS on pwsh 7.0.0

### ISSUE THREAD

**Issue by schmimps** [PowerShell/PSReadLine#1428]
# Steps to reproduce

On iOS, use any iOS RDP app (ms Remote Desktop or Parallels client for example) to access a Windows 10 64bits host. Open Powershell 7.0.0 and type anything. Keyboard doesn’t work. It works with Powershell 6.4 for example as for any other application 

The command https://github.com/PowerShell/PSReadLine/issues/1428#issuecomment-603160883 indicates this is a regression in newer version of PSReadLine (or .NET Core 3.1).

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dgoldman-msft** [comment]
I am able to reproduce this on Mac OS High Sierra connecting to Windows 10 64 bit Version 2004 (oS Build 19041.450). Removing PSReadline however does correct the issue. If i downgrade to PSReadline 2.0.0 the problem goes away, it is present on 2.0.2

c:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

@daxian-dbw, and way to add this issue? I have a confirmed sustainable repro.

**Comment by daxian-dbw** [comment]
Chatted with @dgoldman-msft offline and it looks this is a regression from 2.0.1 to 2.0.0.

**Comment by OchoaJason** [comment]
I am also running into this issue with powershell 7.1.3 when I RDP to the system using ARM WVD Web Client.  I do not get the issue when I RDP using the 'Remote Desktop' modern app.  I tried upgrading PSReadLine to 2.2.0-beta and that did not fix the issue.  Removing the PSReadLine module resolved the issue for both PowerShell (5.1.19041.906) and also pwsh.

**Comment by Bridug** [comment]
I experience this issue with 7.1.3 as well on a 4th Gen iPad Air, iPadOS 14.6 connecting via MS RDP app . PS7 will not take input from the magic keyboard or even the soft keyboard.

**Comment by SteveL-MSFT** [comment]
I'm able to repro this.  The interesting thing is that if you use Windows Terminal, then PS7 w/ PSRL2.2 works fine, just not in the old conhost.  Also, up arrow and enter works, just not alpha keys.

**Comment by dgoldman-msft** [comment]
Steve let me check. I just checked and with you 7.13 with PSR2.1 and above in windows terminal works, still not the old way.

Thanks
Dave
________________________________

**Comment by SteveL-MSFT** [comment]
I would suggest using Windows Terminal until we can figure out what changed between 2.0.0 and 2.0.1 that regressed this

**Comment by SteveL-MSFT** [comment]
It appears the regression is between 2.0.0 and 1.2.0 and not between 2.0.0 and 2.0.1.  This makes it a lot harder to track down the specific change as there were substantial changes between 1.2 and 2.0.

**Comment by SteveL-MSFT** [comment]
Ok, figured out the problem.  Seems like an easy fix.  PR soon.

**Comment by ghost** [comment]
:tada: This issue was addressed in 2632, which has now been successfully released in [`v2.2.0-beta4`](https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta4). :tada:

**Comment by fplanque** [comment]
October 2022: still can't type into a Powershell on Windows 11 (fully up to date) when using Remote Desktop from mac.

Oddly enough, I can scroll through the history with arrow up & down , backspace/delete , CTRL+C also works but any printable character gets ignored.

Same with PowerShell 7.2.6.

**Comment by fplanque** [comment]
If this can help someone:

- Workaround: In Remote Desktop Client, change Keyboard Mode to Scancode instead of Unicode and you can type... 
- Drawback: any keyboard differences (special chars) between Mac and PC standard keyboards will produce the wrong character. Good luck finding the backslash `\` in Scancode mode ! :( 

<img width="1076" alt="2022-10-20_23-48-50" src="https://user-images.githubusercontent.com/1156771/197066685-c313ddbd-e125-449f-a9dd-98dfe63fd1d7.png">

**Comment by daxian-dbw** [comment]
@fplanque Please make sure you are using the latest PSReadLine module (2.2.6 at the moment).
The PSReadLine shipped with PowerShell 7.2.6 is 2.1.0, which doesn't contain this fix.

**Comment by fplanque** [comment]
@daxian-dbw I would like to but I am a new user and I have no idea what the PSReadLine module is and how to update it. Can you point me into the right direction? Thank you.

**Comment by daxian-dbw** [comment]
Open up the 7.2.6 PowerShell on you Win11 machine, then run the following command:
```pwsh
Install-Module PSReadLine -RequiredVersion 2.2.6 -Scope CurrentUser
```
Then start a new PowerShell session, and run the following command to verify the version of PSReadLine you are using:
```
Get-Module PSReadLine  ## you should see 2.2.6
```

**Comment by loaderladdy** [comment]
I have been looking for the answer to this problem for so long.  The thread for this issue has made me so very happy.
Thank you all.
am now off to upgrade PSReadline on several computers.

**Comment by dvmbro** [comment]
@daxian-dbw Thank you! Worked fabulously.
