### ISSUE TITLE
Strange error if command is larger than screen

### ISSUE THREAD

**Issue by NicoNekoru** [PowerShell/PSReadLine#1732]
If I am running something that ends up having a size greater than the window, the terminal will just kinda break. Probably already has been an issue reported since this has occurred for a while now for me but just noting my experiences.

# Environment
Current WT I'm using is the Windows Terminal 1.1.2021.0 from the Windows Store in Windows 10 Pro Version 2004
```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

# Steps to reproduce
To reproduce this error all you need to do is have an open double quote and hold enter until the `>>`s fill the whole screen. If <kbd>ENTER</kbd> doesn't work use <kbd>SHIFT-ENTER</kbd>
![image](https://user-images.githubusercontent.com/66227158/89453906-256ac880-d71d-11ea-85ca-bf4bf682c37c.png)
and when it fills the whole screen the bug will trigger
![image](https://user-images.githubusercontent.com/66227158/89453960-3adff280-d71d-11ea-9ce5-c75a45226fbb.png)

# Behaviour

You can no longer continuously edit parts lower than the bottom `>>`
![image](https://user-images.githubusercontent.com/66227158/89454071-6367ec80-d71d-11ea-8bf9-daee40fd611a.png)
(I clicked 'f' then it immediately put my buffer at the bottom)
The error message
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 57 Keys:
 c d . . Enter
 c d N e LeftArrow LeftArrow Space RightArrow DownArrow RightArrow k o Enter
 " Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow f

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/66227158/89454169-8eead700-d71d-11ea-8d9a-774dd7529608.png)

Or something similar will appear even though it doesn't in normal PowerShell
![image](https://user-images.githubusercontent.com/66227158/89454276-b5a90d80-d71d-11ea-9ed6-14a2d07c3915.png)
![image](https://user-images.githubusercontent.com/66227158/89454309-be014880-d71d-11ea-8eca-7228bde9498a.png)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by NicoNekoru** [comment]
@daxian-dbw Nope, still broken. Fixed some issues but still broken
![image](https://user-images.githubusercontent.com/66227158/92013726-66013600-ed0b-11ea-8f23-3aca3213173a.png)

**Comment by daxian-dbw** [comment]
@NicoNekoru The GitHub URL shown in your screenshot indicates that you were still using an very old version of PSReadLine (2.2.0-beta2 or prior). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery.

**Comment by NicoNekoru** [comment]
Note: the time I made this post was 3 months ago under the windows terminal powershell environment. The issue is better now but still occurs on very large buffer sizes and sometimes after clearing the buffer a few times ina row with ctrl-l
