### ISSUE TITLE
Failed installation of PS 7.3

### ISSUE THREAD

**Issue by DevonAleshire** [PowerShell/PSReadLine#3497]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Updated to Version 7.3 and am unable to run PowerShell due to PSReadline error. I tried to delete the PSReadline module and reinstall based on similar issues identified on GH, but still receiving the same error.
```

### Screenshot

![image](https://user-images.githubusercontent.com/7697694/204403473-9f12cde3-9d4a-4930-bcea-a56b5d158a6e.png)

### Environment data

```console
PS Version: 5.1.22621.608 - NOT ACCURATE - unable to execute the PS script on version 7.3 due to error
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

Installed version 7.3

### Expected behavior

No error when running PS

### Actual behavior

PSReadline Error

**Comment by daxian-dbw** [comment]
This is because the 2.2.0-beta1 version of PSReadLine was outdated version. Please remove that version of PSReadLine, and then 7.3 should be working fine.

**Comment by DevonAleshire** [comment]
Tried deleting the module from C:\Program Files\PowerShell\7 - still getting error. Is it stored anywhere else? The only other version I see is in the side by side folder WinSxS but that is ModuleVersion = '2.0.0'

I will try restarting as well.

**Comment by daxian-dbw** [comment]
The modules in `C:\Program Files\PowerShell\7` are those come along with PS 7.3, and they should be the latest.

To find the outdated PSReadLine module, do the following:
1. start cmd.exe
2. run `pwsh -noprofile -noninteractive` in cmd.exe, which starts powershell in non-interactive mode and thus doesn't auto-load PSReadLine.
3. run `gmo psreadline -list`. This will show you all the PSReadLine versions that can be found in your module path

**Comment by DevonAleshire** [comment]
Perfect! @daxian-dbw, that did the trick 🙂☕. Thank you!
