### ISSUE TITLE
MenuComplete doesn't clear background when moving between items on PowerShell Core

### ISSUE THREAD

**Issue by trha** [PowerShell/PSReadLine#555]
Environment data
----------------
PS version: 6.0.0-beta
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version:

Steps to reproduce or exception report
--------------------------------------
`Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete` then use Tab to cycle between items. 
![ezgif-4-d58c00018f](https://user-images.githubusercontent.com/9519031/30434429-ddedf4d2-9999-11e7-92c3-56b6a659eada.gif)

**Comment by lzybkr** [comment]
This is fixed in the ansi_render branch - I'm not sure when it will be ready for release, but you can try it out now - build it yourself or grab a build out of appveyor. There is some extra work to drop these bits into PSCore (compared to Windows PowerShell), but it's somewhat obvious - you are just replacing the binaries.

**Comment by trha** [comment]
Thanks! I'll try it out.

**Comment by ForNeVeR** [comment]
I can still reproduce the issue in the module version bundled with the released PowerShell Core 6.0. What actions should we take next? Should I file a bug to PowerShell Core repo?

**Comment by lzybkr** [comment]
Run `Install-Module PSReadLine -Force -AllowClobber -AllowPrerelease` and you'll have the 2.0.0-beta1 with the fix.

**Comment by ForNeVeR** [comment]
Yes, it fixed the issue, thanks!

**Comment by rkeithhill** [comment]
That install command fails on Linux.  Do you recommend running pwsh with sudo and then run that command or just install per user?  Hmm, I've tried both of these scenarios in WSL/Ubuntu 16.04 with 6.0.0 GA installed and neither result in PSRL 2.0.0-beta1 getting loaded at startup.
