### ISSUE TITLE
Alt+UpArrow is not recognized

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/PSReadLine#558]
PS version: 5.1.16288.1
PSReadline version: 1.2
os: 10.0.16288.1 (WinBuild.160101.0800)
PS file version: 10.0.16288.1 (WinBuild.160101.0800)

I am unable to set the psreadline shortcut key "alt+uparrow" for complete function.. 
fyi, "ctrl+UpArrow" works..

PS C:\Users\bagajjal> Set-PSReadlineKeyHandler -Chord 'Alt+UpArrow' -Function Complete

**Comment by lzybkr** [comment]
I'm not sure this can be supported easily - `Console.ReadKey` doesn't return when you type `Alt+UpArrow`.

Pure speculation - but I would guess the Alt+numpad support in .Net gets in the way of this working.

I may move away from `Console.ReadKey` at some point, but those plans will force depending on Win10 Creators Update or later.

**Comment by parkovski** [comment]
This is supported now if you set the environment variable `PSREADLINE_VTINPUT=1` before starting PowerShell.

**Comment by favorini** [comment]
@parkovski This didn't work for me, since setting PSREADLINE_VTINPUT=1 causes Ctrl+0 (or other numbers) in PSReadLine to crash PowerShell.exe. This is with PSReadLine 2.0.0 (final, not beta) on Windows 10 v1909 x64.

**Comment by daxian-dbw** [comment]
Closing this issue as we have no plan to moving from `Console.ReadKey`.
@favorini I just tried with the 2.2.2 version of PSReadLine, and `Ctrl+0` doesn't crash with `PSREADLINE_VTINPUT=1` being set on Windows. Maybe that was fixed at some point.

**Comment by favorini** [comment]
@daxian-dbw Still crashed for me on PSReadLine 2.2.2, PowerShell 5.1.19041.1320, Windows 10 v2009.

**Comment by daxian-dbw** [comment]
I found it did crash in console host, but not in Windows Terminal.
